# Build pipeline

name: webstore-build

on:
    workflow_dispatch:

jobs:
    build:
        name: 'Build and Public our App'
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@3.5.3

            - name: restore
              run: dotnet restore

            - run: dotnet build --configuration Release
              name: build

            - run: dotnet public --configuration Release -o ./webstore
              name: publish

            - name: upload build artifact
              uses: actions/upload-artifact@v6.0.0
              with:
                name: webstore
                path: ./webstore
